### ISSUE TITLE
Hompage: Add content to carousel

### ISSUE THREAD

**Issue by chad-cognition** [ki-tools/set#17]

**Comment by chad-cognition** [comment]
[HBGDki SET Homepage Revision Sketches_22Jan2019.pptx](https://github.com/ki-tools/set/files/3457832/HBGDki.SET.Homepage.Revision.Sketches_22Jan2019.pptx)

These define the presets for the 3 use cases for the carousel at the bottom of the homepage.

**Comment by hafen** [comment]
As I've been adding these in I have noticed that it says things like:

"Select Interventions: Exclusive breastfeeding (The following health outcomes (should) populate: Asthma, Diarrhea/diarrheal diseases, Impaired cognitive development/cognitive delay, Necrotizing enterocolitis, Otitis Media, Pneumonia/lower respiratory infections, Protein energy malnutrition, RSV Infection/ Bronchiolitis"

and

"Select Malnutrition as a risk factor (instead of a health outcome) by searching “Malnutrition”, “Undernutrition” and “Poor Nutritional Status”. The following health outcomes (should populate): Tuberculosis, Pneumonia, Measles, Leishmaniasis, RSV Infections, Diarrheal Disease, Helminth Infections."

This tells me that the expected behavior is that when a risk factor is chosen, all of its associated health outcomes should automatically be added to the timeline as well. Is this true? because this is not what is being done right now. Further, if any of the health outcomes, risk factors, interventions, or pathogeneses are selected, should all others in that graph be added to the timeline as well?

**Comment by hafen** [comment]
These have been added and the style has been updated to use the full width of the app. Now we just need images so I'll refer this back to @chad-cognition.

**Comment by chad-cognition** [comment]
@hafen: Here's a folder of images for the homepage. Don't hate me, but I had to make a design update. It was too difficult to make the text over the image work well. So, I separated them out into separate blocks. Let me know if this is too difficult to change and I can see what I can do. There's an updated prototype on Invision here. You can click through the carousel to see which photo goes with which text: https://invis.io/BAPLMK56G5U#/395288665_SET_Home_Copy_2

[To Dev.zip](https://github.com/ki-tools/set/files/3894342/To.Dev.zip)
